//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WenEnvios.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        public Cliente()
        {
            this.Producto = new HashSet<Producto>();
            this.Producto1 = new HashSet<Producto>();
        }

        [Display(Name = "#")]
    
        public int IDCliente { get; set; }
        [Display(Name = "Nombre del Cliente")]
        public string CNombre { get; set; }
        [Display(Name = "Apellido del Cliente")]
        public string CApellido { get; set; }
        [Display(Name = "Telefono")]
        public Nullable<int> CTelefono { get; set; }
        [Display(Name = "Correo")]
       
        public string Ccorreo { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual ICollection<Producto> Producto1 { get; set; }
    }
}
