//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WenEnvios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Descuento
    {
        public Descuento()
        {
            this.Producto = new HashSet<Producto>();
            this.Producto1 = new HashSet<Producto>();
        }
    
        public int IDescuento { get; set; }
        public Nullable<double> Descuento1 { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual ICollection<Producto> Producto1 { get; set; }
    }
}
