//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WenEnvios.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        [Display(Name = "#")]
        public int IDProduto { get; set; }
        [Display(Name = "Tipo de producto")]
        public int TPProducto { get; set; }
        [Display(Name = "Id de cliente")]
        public int IDProducto { get; set; }
        [Display(Name = "Tipo de envio")]
        public int TEEnvio { get; set; }
        [Display(Name = "Bodega")]
        public string PBodegaEntrega { get; set; }
        [Display(Name = "Placa")]
        public string Placa { get; set; }
        [Display(Name = "Puerto")]
        public string PPuertoEntrega { get; set; }
        [Display(Name = "Numero Flota")]
        public Nullable<int> PNumeroFlota { get; set; }
        [Display(Name = "# de Gui")]
        public string PNoGuia { get; set; }
        [Display(Name = "precio")]
        public Nullable<int> Precio { get; set; }
        [Display(Name = "Cantidad")]
        public Nullable<int> Cantidad { get; set; }
        [Display(Name = "Descuento")]
        public Nullable<int> Descuento { get; set; }
        [Display(Name = "Total")]
        public Nullable<int> Total { get; set; }
        [Display(Name = "Fecha")]
        public Nullable<System.DateTime> PFechaRegistro { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual Descuento Descuento1 { get; set; }
        public virtual Descuento Descuento2 { get; set; }
        public virtual TipoEnvio TipoEnvio { get; set; }
        public virtual TipoEnvio TipoEnvio1 { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
        public virtual TipoProducto TipoProducto1 { get; set; }
        public virtual TipoProducto TipoProducto2 { get; set; }
    }
}
